// Mocks generated by Mockito 5.4.4 from annotations
// in nb_maps_flutter/test/controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:math' as _i7;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i8;

import 'package:flutter/foundation.dart' as _i4;
import 'package:flutter/gestures.dart' as _i6;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nb_maps_flutter/nb_maps_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArgumentCallbacks_0<T> extends _i1.SmartFake
    implements _i2.ArgumentCallbacks<T> {
  _FakeArgumentCallbacks_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_1 extends _i1.SmartFake implements _i3.Widget {
  _FakeWidget_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i4.DiagnosticLevel? minLevel = _i4.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [NbMapsGlPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockNbMapsGlPlatform extends _i1.Mock implements _i2.NbMapsGlPlatform {
  MockNbMapsGlPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ArgumentCallbacks<String> get onInfoWindowTappedPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onInfoWindowTappedPlatform),
        returnValue: _FakeArgumentCallbacks_0<String>(
          this,
          Invocation.getter(#onInfoWindowTappedPlatform),
        ),
      ) as _i2.ArgumentCallbacks<String>);

  @override
  _i2.ArgumentCallbacks<Map<String, dynamic>> get onFeatureTappedPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onFeatureTappedPlatform),
        returnValue: _FakeArgumentCallbacks_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#onFeatureTappedPlatform),
        ),
      ) as _i2.ArgumentCallbacks<Map<String, dynamic>>);

  @override
  _i2.ArgumentCallbacks<Map<String, dynamic>> get onFeatureDraggedPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onFeatureDraggedPlatform),
        returnValue: _FakeArgumentCallbacks_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#onFeatureDraggedPlatform),
        ),
      ) as _i2.ArgumentCallbacks<Map<String, dynamic>>);

  @override
  _i2.ArgumentCallbacks<void> get onCameraMoveStartedPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onCameraMoveStartedPlatform),
        returnValue: _FakeArgumentCallbacks_0<void>(
          this,
          Invocation.getter(#onCameraMoveStartedPlatform),
        ),
      ) as _i2.ArgumentCallbacks<void>);

  @override
  _i2.ArgumentCallbacks<_i2.CameraPosition> get onCameraMovePlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onCameraMovePlatform),
        returnValue: _FakeArgumentCallbacks_0<_i2.CameraPosition>(
          this,
          Invocation.getter(#onCameraMovePlatform),
        ),
      ) as _i2.ArgumentCallbacks<_i2.CameraPosition>);

  @override
  _i2.ArgumentCallbacks<_i2.CameraPosition?> get onCameraIdlePlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onCameraIdlePlatform),
        returnValue: _FakeArgumentCallbacks_0<_i2.CameraPosition?>(
          this,
          Invocation.getter(#onCameraIdlePlatform),
        ),
      ) as _i2.ArgumentCallbacks<_i2.CameraPosition?>);

  @override
  _i2.ArgumentCallbacks<void> get onMapStyleLoadedPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onMapStyleLoadedPlatform),
        returnValue: _FakeArgumentCallbacks_0<void>(
          this,
          Invocation.getter(#onMapStyleLoadedPlatform),
        ),
      ) as _i2.ArgumentCallbacks<void>);

  @override
  _i2.ArgumentCallbacks<Map<String, dynamic>> get onMapClickPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onMapClickPlatform),
        returnValue: _FakeArgumentCallbacks_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#onMapClickPlatform),
        ),
      ) as _i2.ArgumentCallbacks<Map<String, dynamic>>);

  @override
  _i2.ArgumentCallbacks<Map<String, dynamic>> get onMapLongClickPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onMapLongClickPlatform),
        returnValue: _FakeArgumentCallbacks_0<Map<String, dynamic>>(
          this,
          Invocation.getter(#onMapLongClickPlatform),
        ),
      ) as _i2.ArgumentCallbacks<Map<String, dynamic>>);

  @override
  _i2.ArgumentCallbacks<void> get onAttributionClickPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onAttributionClickPlatform),
        returnValue: _FakeArgumentCallbacks_0<void>(
          this,
          Invocation.getter(#onAttributionClickPlatform),
        ),
      ) as _i2.ArgumentCallbacks<void>);

  @override
  _i2.ArgumentCallbacks<_i2.MyLocationTrackingMode>
      get onCameraTrackingChangedPlatform => (super.noSuchMethod(
            Invocation.getter(#onCameraTrackingChangedPlatform),
            returnValue: _FakeArgumentCallbacks_0<_i2.MyLocationTrackingMode>(
              this,
              Invocation.getter(#onCameraTrackingChangedPlatform),
            ),
          ) as _i2.ArgumentCallbacks<_i2.MyLocationTrackingMode>);

  @override
  _i2.ArgumentCallbacks<void> get onCameraTrackingDismissedPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onCameraTrackingDismissedPlatform),
        returnValue: _FakeArgumentCallbacks_0<void>(
          this,
          Invocation.getter(#onCameraTrackingDismissedPlatform),
        ),
      ) as _i2.ArgumentCallbacks<void>);

  @override
  _i2.ArgumentCallbacks<void> get onMapIdlePlatform => (super.noSuchMethod(
        Invocation.getter(#onMapIdlePlatform),
        returnValue: _FakeArgumentCallbacks_0<void>(
          this,
          Invocation.getter(#onMapIdlePlatform),
        ),
      ) as _i2.ArgumentCallbacks<void>);

  @override
  _i2.ArgumentCallbacks<_i2.UserLocation> get onUserLocationUpdatedPlatform =>
      (super.noSuchMethod(
        Invocation.getter(#onUserLocationUpdatedPlatform),
        returnValue: _FakeArgumentCallbacks_0<_i2.UserLocation>(
          this,
          Invocation.getter(#onUserLocationUpdatedPlatform),
        ),
      ) as _i2.ArgumentCallbacks<_i2.UserLocation>);

  @override
  _i5.Future<void> initPlatform(int? id) => (super.noSuchMethod(
        Invocation.method(
          #initPlatform,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.Widget buildView(
    Map<String, dynamic>? creationParams,
    _i2.OnPlatformViewCreatedCallback? onPlatformViewCreated,
    Set<_i4.Factory<_i6.OneSequenceGestureRecognizer>>? gestureRecognizers,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildView,
          [
            creationParams,
            onPlatformViewCreated,
            gestureRecognizers,
          ],
        ),
        returnValue: _FakeWidget_1(
          this,
          Invocation.method(
            #buildView,
            [
              creationParams,
              onPlatformViewCreated,
              gestureRecognizers,
            ],
          ),
        ),
      ) as _i3.Widget);

  @override
  _i5.Future<_i2.CameraPosition?> updateMapOptions(
          Map<String, dynamic>? optionsUpdate) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMapOptions,
          [optionsUpdate],
        ),
        returnValue: _i5.Future<_i2.CameraPosition?>.value(),
      ) as _i5.Future<_i2.CameraPosition?>);

  @override
  _i5.Future<bool?> animateCamera(
    _i2.CameraUpdate? cameraUpdate, {
    Duration? duration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #animateCamera,
          [cameraUpdate],
          {#duration: duration},
        ),
        returnValue: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<bool?> moveCamera(_i2.CameraUpdate? cameraUpdate) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveCamera,
          [cameraUpdate],
        ),
        returnValue: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);

  @override
  _i5.Future<void> updateMyLocationTrackingMode(
          _i2.MyLocationTrackingMode? myLocationTrackingMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMyLocationTrackingMode,
          [myLocationTrackingMode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> matchMapLanguageWithDeviceDefault() => (super.noSuchMethod(
        Invocation.method(
          #matchMapLanguageWithDeviceDefault,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void resizeWebMap() => super.noSuchMethod(
        Invocation.method(
          #resizeWebMap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void forceResizeWebMap() => super.noSuchMethod(
        Invocation.method(
          #forceResizeWebMap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> updateContentInsets(
    _i3.EdgeInsets? insets,
    bool? animated,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContentInsets,
          [
            insets,
            animated,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMapLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setMapLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setTelemetryEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setTelemetryEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getTelemetryEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getTelemetryEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<dynamic>> queryRenderedFeatures(
    _i7.Point<double>? point,
    List<String>? layerIds,
    List<Object>? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryRenderedFeatures,
          [
            point,
            layerIds,
            filter,
          ],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> queryRenderedFeaturesInRect(
    _i8.Rect? rect,
    List<String>? layerIds,
    String? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryRenderedFeaturesInRect,
          [
            rect,
            layerIds,
            filter,
          ],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<dynamic> invalidateAmbientCache() => (super.noSuchMethod(
        Invocation.method(
          #invalidateAmbientCache,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<_i2.LatLng?> requestMyLocationLatLng() => (super.noSuchMethod(
        Invocation.method(
          #requestMyLocationLatLng,
          [],
        ),
        returnValue: _i5.Future<_i2.LatLng?>.value(),
      ) as _i5.Future<_i2.LatLng?>);

  @override
  _i5.Future<_i2.LatLngBounds?> getVisibleRegion() => (super.noSuchMethod(
        Invocation.method(
          #getVisibleRegion,
          [],
        ),
        returnValue: _i5.Future<_i2.LatLngBounds?>.value(),
      ) as _i5.Future<_i2.LatLngBounds?>);

  @override
  _i5.Future<void> setStyleString(String? styleString) => (super.noSuchMethod(
        Invocation.method(
          #setStyleString,
          [styleString],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addImage(
    String? name,
    _i9.Uint8List? bytes, [
    bool? sdf = false,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #addImage,
          [
            name,
            bytes,
            sdf,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addImageSource(
    String? imageSourceId,
    _i9.Uint8List? bytes,
    _i2.LatLngQuad? coordinates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addImageSource,
          [
            imageSourceId,
            bytes,
            coordinates,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateImageSource(
    String? imageSourceId,
    _i9.Uint8List? bytes,
    _i2.LatLngQuad? coordinates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateImageSource,
          [
            imageSourceId,
            bytes,
            coordinates,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addLayer(
    String? imageLayerId,
    String? imageSourceId,
    double? minzoom,
    double? maxzoom,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLayer,
          [
            imageLayerId,
            imageSourceId,
            minzoom,
            maxzoom,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addLayerBelow(
    String? imageLayerId,
    String? imageSourceId,
    String? belowLayerId,
    double? minzoom,
    double? maxzoom,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLayerBelow,
          [
            imageLayerId,
            imageSourceId,
            belowLayerId,
            minzoom,
            maxzoom,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeLayer(String? imageLayerId) => (super.noSuchMethod(
        Invocation.method(
          #removeLayer,
          [imageLayerId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFilter(
    String? layerId,
    dynamic filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilter,
          [
            layerId,
            filter,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVisibility(
    String? layerId,
    bool? isVisible,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setVisibility,
          [
            layerId,
            isVisible,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.Point<num>?> toScreenLocation(_i2.LatLng? latLng) =>
      (super.noSuchMethod(
        Invocation.method(
          #toScreenLocation,
          [latLng],
        ),
        returnValue: _i5.Future<_i7.Point<num>?>.value(),
      ) as _i5.Future<_i7.Point<num>?>);

  @override
  _i5.Future<List<_i7.Point<num>>> toScreenLocationBatch(
          Iterable<_i2.LatLng>? latLngs) =>
      (super.noSuchMethod(
        Invocation.method(
          #toScreenLocationBatch,
          [latLngs],
        ),
        returnValue: _i5.Future<List<_i7.Point<num>>>.value(<_i7.Point<num>>[]),
      ) as _i5.Future<List<_i7.Point<num>>>);

  @override
  _i5.Future<_i2.LatLng?> toLatLng(_i7.Point<num>? screenLocation) =>
      (super.noSuchMethod(
        Invocation.method(
          #toLatLng,
          [screenLocation],
        ),
        returnValue: _i5.Future<_i2.LatLng?>.value(),
      ) as _i5.Future<_i2.LatLng?>);

  @override
  _i5.Future<double?> getMetersPerPixelAtLatitude(double? latitude) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMetersPerPixelAtLatitude,
          [latitude],
        ),
        returnValue: _i5.Future<double?>.value(),
      ) as _i5.Future<double?>);

  @override
  _i5.Future<void> addGeoJsonSource(
    String? sourceId,
    Map<String, dynamic>? geojson, {
    String? promoteId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGeoJsonSource,
          [
            sourceId,
            geojson,
          ],
          {#promoteId: promoteId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setGeoJsonSource(
    String? sourceId,
    Map<String, dynamic>? geojson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setGeoJsonSource,
          [
            sourceId,
            geojson,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setFeatureForGeoJsonSource(
    String? sourceId,
    Map<String, dynamic>? geojsonFeature,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFeatureForGeoJsonSource,
          [
            sourceId,
            geojsonFeature,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeSource(String? sourceId) => (super.noSuchMethod(
        Invocation.method(
          #removeSource,
          [sourceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addSymbolLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
    dynamic filter,
    required bool? enableInteraction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSymbolLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
            #filter: filter,
            #enableInteraction: enableInteraction,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addLineLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
    dynamic filter,
    required bool? enableInteraction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLineLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
            #filter: filter,
            #enableInteraction: enableInteraction,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addCircleLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
    dynamic filter,
    required bool? enableInteraction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCircleLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
            #filter: filter,
            #enableInteraction: enableInteraction,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addFillLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
    dynamic filter,
    required bool? enableInteraction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFillLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
            #filter: filter,
            #enableInteraction: enableInteraction,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addFillExtrusionLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
    dynamic filter,
    required bool? enableInteraction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFillExtrusionLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
            #filter: filter,
            #enableInteraction: enableInteraction,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addRasterLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRasterLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addHillshadeLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHillshadeLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addHeatmapLayer(
    String? sourceId,
    String? layerId,
    Map<String, dynamic>? properties, {
    String? belowLayerId,
    String? sourceLayer,
    double? minzoom,
    double? maxzoom,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addHeatmapLayer,
          [
            sourceId,
            layerId,
            properties,
          ],
          {
            #belowLayerId: belowLayerId,
            #sourceLayer: sourceLayer,
            #minzoom: minzoom,
            #maxzoom: maxzoom,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addSource(
    String? sourceId,
    _i2.SourceProperties? properties,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSource,
          [
            sourceId,
            properties,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> takeSnapshot(_i2.SnapshotOptions? snapshotOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeSnapshot,
          [snapshotOptions],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> findBelowLayerId(List<String>? belowAt) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBelowLayerId,
          [belowAt],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
