name: nb_maps_flutter_example
description: Demonstrates how to use the nb_maps_flutter plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  collection: ^1.0.0
  device_info_plus: ^11.3.0
  nb_maps_flutter:
    path: ../
  path_provider: ^2.0.0
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fill/cat_silhouette_pattern.png
    - assets/fill-extrusion/indoor_3d_map.json
    - assets/symbols/custom-icon.png
    - assets/symbols/location_off.png
    - assets/symbols/location_on.png
    - assets/symbols/2.0x/custom-icon.png
    - assets/symbols/3.0x/custom-icon.png
    - assets/style.json
