name: nb_maps_flutter
description: A Flutter plugin for Nextbillion.ai Maps SDK that provides cross-platform map functionality with custom styles, camera controls, location tracking, and various annotation types.
version: 3.0.0-dev.3
homepage: https://github.com/nextbillion-ai/nextbillion-maps-flutter
repository: https://github.com/nextbillion-ai/nextbillion-maps-flutter

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.6.1
  mockito: 5.4.4
  test: ^1.24.9
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: ai.nextbillion.maps_flutter
        pluginClass: NbMapsPlugin
      ios:
        pluginClass: SwiftNbMapsFlutterPlugin
